package crypto

import (
	"crypto/ecdsa"
)

// Derives a key from a public and private ECDSA key pair. The derived key is
// compatible to the one generated by the subtle crypto API
func DeriveKey(publicKey *ecdsa.PublicKey, privateKey *ecdsa.PrivateKey) []byte {
	a, _ := publicKey.Curve.ScalarMult(publicKey.X, publicKey.Y, privateKey.D.Bytes())
	return a.Bytes()
}
